<a href="https://colab.research.google.com/github/viveksunilkumar1-hue/Assessment2/blob/main/Assessment_2_Vivek_S.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
#Q1. NumPy Array Creation – 2 Marks
#Create a NumPy array containing the following values:
arr=np.array([10,20,30,40,50])
print(arr)
print(arr.shape)
print(arr.dtype)

[10 20 30 40 50]
(5,)
int64

In [3]:
#Q2. NumPy Array Operations – 2 Marks


arr=np.array([5,10,15,20,25])
print(arr+5)
print(arr*2)

[10 15 20 25 30]
[10 20 30 40 50]

In [4]:
#Q3. NumPy Statistical Operations – 2 Marks

arr= np.array([12,15,18,20,25,30])
print("mean:",arr.mean())
print("median:",np.median(arr))
print("Minimum:",arr.min())
print("Maximum:",arr.max())
print("Standard Deviation:",arr.std())

mean: 20.0
median: 19.0
Minimum: 12
Maximum: 30
Standard Deviation: 6.027713773341708

In [5]:
#Q4. NumPy Filtering – 2 Marks
#Given:
#arr = np.array([10, 25, 30, 45, 50, 65, 70])
#Using NumPy, extract all values that are greater than 40.

arr = np.array([10, 25, 30, 45, 50, 65, 70])
arr[arr>40]

array([45, 50, 65, 70])

In [6]:
#Q5. Create a Pandas DataFrame – 2 Marks
#Create the following DataFrame using Pandas:


df=pd.DataFrame({'Name':['Anu','Rahul','Meera','Arun'],'Age':[21,22,20,23],'Score':[85,72,91,68]})
df

    Name  Age  Score
0    Anu   21     85
1  Rahul   22     72
2  Meera   20     91
3   Arun   23     68

In [7]:
#Q6. DataFrame Selection – 2 Marks
#Using the DataFrame created in Q5:
#1. Display only the Name and Score columns.
#2. Display the complete record of Meera

df=pd.DataFrame({'Name':['Anu','Rahul','Meera','Arun'],'Age':[21,22,20,23],'Score':[85,72,91,68]})
print(df[['Name','Score']])
print(df[df['Name']=='Meera'])

    Name  Score
0    Anu     85
1  Rahul     72
2  Meera     91
3   Arun     68
    Name  Age  Score
2  Meera   20     91

In [8]:
#Q7. DataFrame Filtering – 2 Marks
#Using the DataFrame from Q5, display all students whose Score is greater than 75

df=pd.DataFrame({'Name':['Anu','Rahul','Meera','Arun'],'Age':[21,22,20,23],'Score':[85,72,91,68]})
df[df['Score']>75]

    Name  Age  Score
0    Anu   21     85
2  Meera   20     91

In [15]:
#Q8. DataFrame Inspection – 2 Marks
#Using the DataFrame from Q5, display:


df=pd.DataFrame({'Name':['Anu','Rahul','Meera','Arun'],'Age':[21,22,20,23],'Score':[85,72,91,68]})
print(df.shape)
print(df.columns)
print(df.dtypes)
print(df.describe())

(4, 3)
Index(['Name', 'Age', 'Score'], dtype='object')
Name     object
Age       int64
Score     int64
dtype: object
             Age      Score
count   4.000000   4.000000
mean   21.500000  79.000000
std     1.290994  10.801234
min    20.000000  68.000000
25%    20.750000  71.000000
50%    21.500000  78.500000
75%    22.250000  86.500000
max    23.000000  91.000000

In [13]:
#Q9. Sorting a DataFrame – 2 Marks
#Sort the DataFrame from Q5 by
#Score in descending order.

df.sort_values(by='Score',ascending=False)

    Name  Age  Score
2  Meera   20     91
0    Anu   21     85
1  Rahul   22     72
3   Arun   23     68

In [19]:
#Q10. Handling Missing Values – 2 Marks
#Consider the following DataFrame:


df = pd.DataFrame({
'Name': ['A', 'B', 'C', 'D'],
'Age': [21, np.nan, 23, 22],
'Score': [80, 75, np.nan, 90]})
print(df.isnull())
print(df['Age'].fillna(df['Age'].mean()))
print(df['Score'].fillna(df['Score'].mean()))

    Name    Age  Score
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False
0    21.0
1    22.0
2    23.0
3    22.0
Name: Age, dtype: float64
0    80.000000
1    75.000000
2    81.666667
3    90.000000
Name: Score, dtype: float64

In [16]:
#Q11. Data Loading and Exploration – 6 Marks
#Load student_performance.csv into a Pandas DataFrame.


file_path='/content/student_performance.csv'
df=pd.read_csv(file_path)
print(df.head())
print(df.tail())
print(df.shape)
print(df.columns)
print(df.dtypes)
print(df.describe)

  Student_ID            Name  Gender        Department   Age  Attendance  \
0    STU1001     Rahul Varma    Male  Computer Science  25.0        74.7
1    STU1002    Kiran Pillai    Male  Computer Science  24.0        75.5
2    STU1003  Fathima Joseph  Female       Electronics  21.0        60.5
3    STU1004    Rahul Sharma  Female      Data Science  25.0        80.4
4    STU1005       Asha Nair  Female      Data Science  22.0        71.4

   Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
0          89.4       86.3          81.9         76.7         82.7
1          70.3       63.1          65.1         62.3         60.3
2          79.9       80.4          65.3         68.0         67.1
3          65.8       50.7          52.6         48.8         57.2
4          90.1       82.9          72.4         87.7         81.9
   Student_ID            Name  Gender        Department   Age  Attendance  \
75    STU1076     Priya Kumar  Female  Computer Science  24.0        99.3
76    STU1077      Amal Kumar    Male      Data Science   NaN        93.8
77    STU1078  Fathima Sharma    Male  Computer Science  19.0        86.4
78    STU1079    Meera Thomas    Male       Electronics  23.0        99.4
79    STU1080      Diya Varma    Male       Electronics  19.0        86.4

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
75          46.9       57.6          29.5         57.1         47.2
76          45.8       43.4          58.1         38.8         43.5
77          70.4       75.7          98.2         76.7         75.2
78          64.6       66.5          61.8         52.5         63.4
79          80.5       94.3          58.6         74.9         78.6
(80, 11)
Index(['Student_ID', 'Name', 'Gender', 'Department', 'Age', 'Attendance',
       'Python_Score', 'SQL_Score', 'Pandas_Score', 'NumPy_Score',
       'Final_Score'],
      dtype='object')
Student_ID       object
Name             object
Gender           object
Department       object
Age             float64
Attendance      float64
Python_Score    float64
SQL_Score       float64
Pandas_Score    float64
NumPy_Score     float64
Final_Score     float64
dtype: object
<bound method NDFrame.describe of    Student_ID            Name  Gender        Department   Age  Attendance  \
0     STU1001     Rahul Varma    Male  Computer Science  25.0        74.7
1     STU1002    Kiran Pillai    Male  Computer Science  24.0        75.5
2     STU1003  Fathima Joseph  Female       Electronics  21.0        60.5
3     STU1004    Rahul Sharma  Female      Data Science  25.0        80.4
4     STU1005       Asha Nair  Female      Data Science  22.0        71.4
..        ...             ...     ...               ...   ...         ...
75    STU1076     Priya Kumar  Female  Computer Science  24.0        99.3
76    STU1077      Amal Kumar    Male      Data Science   NaN        93.8
77    STU1078  Fathima Sharma    Male  Computer Science  19.0        86.4
78    STU1079    Meera Thomas    Male       Electronics  23.0        99.4
79    STU1080      Diya Varma    Male       Electronics  19.0        86.4

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
0           89.4       86.3          81.9         76.7         82.7
1           70.3       63.1          65.1         62.3         60.3
2           79.9       80.4          65.3         68.0         67.1
3           65.8       50.7          52.6         48.8         57.2
4           90.1       82.9          72.4         87.7         81.9
..           ...        ...           ...          ...          ...
75          46.9       57.6          29.5         57.1         47.2
76          45.8       43.4          58.1         38.8         43.5
77          70.4       75.7          98.2         76.7         75.2
78          64.6       66.5          61.8         52.5         63.4
79          80.5       94.3          58.6         74.9         78.6

[80 rows x 11 columns]>

In [20]:
#Q12. Filtering and Sorting – 6 Marks


file_path='/content/student_performance.csv'
df=pd.read_csv(file_path)
print(df[df['Final_Score']>75])
print(df[df['Attendance']<75])
print(df[(df['Department']=='Data Science')&(df['Final_Score']>80)])
print(df.sort_values(by='Final_Score',ascending=False))

   Student_ID            Name  Gender        Department   Age  Attendance  \
0     STU1001     Rahul Varma    Male  Computer Science  25.0        74.7
4     STU1005       Asha Nair  Female      Data Science  22.0        71.4
6     STU1007     Akhil Varma    Male       Electronics  22.0        73.2
7     STU1008     Akhil Varma    Male  Computer Science  20.0        81.1
8     STU1009      Diya Menon    Male      Data Science  25.0        64.4
10    STU1011        Diya Das  Female      Data Science  20.0       100.0
11    STU1012      Arun Reddy    Male       Electronics  20.0        69.1
16    STU1017    Rahul Thomas  Female      Data Science  25.0        78.3
17    STU1018      Priya Nair    Male      Data Science  19.0        85.4
23    STU1024  Fathima Joseph  Female          Commerce  23.0        78.2
24    STU1025     Kiran Varma  Female       Electronics  21.0        80.7
27    STU1028     Nikhil Nair  Female      Data Science  24.0        79.3
30    STU1031      Amal Varma  Female  Computer Science  19.0        86.7
33    STU1034        Amal Das    Male  Computer Science  19.0        85.5
35    STU1036      Maya Menon  Female       Electronics  19.0        82.0
37    STU1038    Kiran Pillai  Female       Electronics  25.0        85.2
39    STU1040    Rohan Sharma  Female  Computer Science  21.0       100.0
40    STU1041     Amal Pillai  Female  Computer Science  25.0        97.7
41    STU1042     Arun Joseph  Female  Computer Science  21.0        85.9
43    STU1044       Rahul Das  Female  Computer Science  22.0        70.9
47    STU1048     Priya Kumar    Male      Data Science  25.0        64.6
48    STU1049     Asha Sharma    Male      Data Science  22.0        91.3
51    STU1052      Gokul Nair  Female          Commerce  25.0        77.3
55    STU1056     Vivek Varma    Male      Data Science  22.0        81.0
56    STU1057    Rohan Pillai  Female          Commerce  20.0        79.5
57    STU1058     Diya Thomas  Female  Computer Science  23.0        83.5
58    STU1059       Anu Menon    Male       Electronics  24.0        96.7
59    STU1060      Asha Menon    Male      Data Science  19.0        56.3
61    STU1062    Kiran Pillai  Female  Computer Science  19.0        83.8
64    STU1065    Rohan Sharma    Male  Computer Science  19.0        64.4
67    STU1068        Maya Das  Female  Computer Science  23.0        66.7
73    STU1074       Anu Kumar  Female  Computer Science  22.0        95.0
77    STU1078  Fathima Sharma    Male  Computer Science  19.0        86.4
79    STU1080      Diya Varma    Male       Electronics  19.0        86.4

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
0           89.4       86.3          81.9         76.7         82.7
4           90.1       82.9          72.4         87.7         81.9
6           81.7       82.2          81.5         64.2         77.0
7           72.1       80.4          72.9         73.5         79.2
8           94.8       86.0          87.7        100.0         83.0
10         100.0       93.2         100.0         89.3         91.9
11          80.4       78.0          88.9         77.1         86.9
16          80.8       99.4          77.2        100.0         91.1
17          62.6       81.6          79.6         75.5         75.1
23          87.7       71.0          88.5         74.8         83.7
24          87.5       67.1          84.5         96.1         77.3
27          70.3       82.0          64.4         72.8         77.1
30          86.9       64.3         100.0         89.2         85.5
33          94.4       81.6          71.3         81.5         84.3
35          95.3       93.4         100.0         62.5         84.2
37          87.8       78.3          85.5         82.7         82.4
39          68.9       79.8          66.1         66.4         78.5
40          94.3       91.0          73.1         91.2         94.5
41          71.2       76.1          70.8          NaN         77.9
43          68.0       67.3          83.6         76.7         77.3
47          80.6       67.0          71.2         80.2         77.3
48          88.9       95.0           NaN         94.5         97.0
51          80.4       85.3          96.7         83.5         79.3
55          87.0       95.1          88.4         75.7         93.3
56          72.1       66.9          61.8         72.3         75.2
57          93.1       78.8          91.6         83.8         92.3
58          99.7       77.1          68.9         89.7         84.9
59         100.0       85.0          87.4         57.4         87.9
61         100.0      100.0          89.4         91.4         96.0
64          96.5       69.3          86.7         80.7         83.5
67          83.4       79.6          89.3         83.6         83.7
73          95.3       67.7          92.4         81.4         83.4
77          70.4       75.7          98.2         76.7         75.2
79          80.5       94.3          58.6         74.9         78.6
   Student_ID            Name    Gender        Department   Age  Attendance  \
0     STU1001     Rahul Varma      Male  Computer Science  25.0        74.7
2     STU1003  Fathima Joseph    Female       Electronics  21.0        60.5
4     STU1005       Asha Nair    Female      Data Science  22.0        71.4
6     STU1007     Akhil Varma      Male       Electronics  22.0        73.2
8     STU1009      Diya Menon      Male      Data Science  25.0        64.4
9     STU1010    Gokul Pillai    Female  Computer Science  19.0        67.3
11    STU1012      Arun Reddy      Male       Electronics  20.0        69.1
15    STU1016    Nikhil Kumar    Female  Computer Science   NaN        70.3
19    STU1020    Vivek Sharma    Female          Commerce  22.0        72.1
25    STU1026      Maya Menon      Male       Electronics  20.0        68.3
36    STU1037    Nikhil Menon      Male       Electronics  22.0        74.8
42    STU1043     Sneha Varma   female       Data Science  19.0        74.4
43    STU1044       Rahul Das    Female  Computer Science  22.0        70.9
47    STU1048     Priya Kumar      Male      Data Science  25.0        64.6
50    STU1051     Gokul Menon      Male      Data Science  25.0        70.9
59    STU1060      Asha Menon      Male      Data Science  19.0        56.3
64    STU1065    Rohan Sharma      Male  Computer Science  19.0        64.4
67    STU1068        Maya Das    Female  Computer Science  23.0        66.7
71    STU1072    Vivek Pillai      Male          Commerce  24.0        71.5

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
0           89.4       86.3          81.9         76.7         82.7
2           79.9       80.4          65.3         68.0         67.1
4           90.1       82.9          72.4         87.7         81.9
6           81.7       82.2          81.5         64.2         77.0
8           94.8       86.0          87.7        100.0         83.0
9           79.6       85.0          74.1         80.5         73.8
11          80.4       78.0          88.9         77.1         86.9
15          55.9       69.3          67.1         58.4         58.2
19          65.8       60.9          49.8         44.8         54.6
25          91.7       64.5          83.5         73.7         69.4
36          69.5       60.7          64.6         81.6         69.1
42          71.8       79.1          69.8         95.9          NaN
43          68.0       67.3          83.6         76.7         77.3
47          80.6       67.0          71.2         80.2         77.3
50          68.6       81.0          64.0         63.0         70.5
59         100.0       85.0          87.4         57.4         87.9
64          96.5       69.3          86.7         80.7         83.5
67          83.4       79.6          89.3         83.6         83.7
71          59.0       58.2          56.3         48.9         56.6
   Student_ID          Name  Gender    Department   Age  Attendance  \
4     STU1005     Asha Nair  Female  Data Science  22.0        71.4
8     STU1009    Diya Menon    Male  Data Science  25.0        64.4
10    STU1011      Diya Das  Female  Data Science  20.0       100.0
16    STU1017  Rahul Thomas  Female  Data Science  25.0        78.3
48    STU1049   Asha Sharma    Male  Data Science  22.0        91.3
55    STU1056   Vivek Varma    Male  Data Science  22.0        81.0
59    STU1060    Asha Menon    Male  Data Science  19.0        56.3

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
4           90.1       82.9          72.4         87.7         81.9
8           94.8       86.0          87.7        100.0         83.0
10         100.0       93.2         100.0         89.3         91.9
16          80.8       99.4          77.2        100.0         91.1
48          88.9       95.0           NaN         94.5         97.0
55          87.0       95.1          88.4         75.7         93.3
59         100.0       85.0          87.4         57.4         87.9
   Student_ID           Name    Gender        Department   Age  Attendance  \
48    STU1049    Asha Sharma      Male      Data Science  22.0        91.3
61    STU1062   Kiran Pillai    Female  Computer Science  19.0        83.8
40    STU1041    Amal Pillai    Female  Computer Science  25.0        97.7
55    STU1056    Vivek Varma      Male      Data Science  22.0        81.0
57    STU1058    Diya Thomas    Female  Computer Science  23.0        83.5
..        ...            ...       ...               ...   ...         ...
34    STU1035   Rahul Pillai    Female      Data Science  22.0        82.5
76    STU1077     Amal Kumar      Male      Data Science   NaN        93.8
26    STU1027  Aditya Pillai    Female  Computer Science  25.0        79.6
42    STU1043    Sneha Varma   female       Data Science  19.0        74.4
53    STU1054    Maya Sharma      Male      Data Science  19.0        82.5

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
48          88.9       95.0           NaN         94.5         97.0
61         100.0      100.0          89.4         91.4         96.0
40          94.3       91.0          73.1         91.2         94.5
55          87.0       95.1          88.4         75.7         93.3
57          93.1       78.8          91.6         83.8         92.3
..           ...        ...           ...          ...          ...
34          41.4       44.4          53.8         43.2         44.2
76          45.8       43.4          58.1         38.8         43.5
26          44.0       52.5          25.0         25.0         40.6
42          71.8       79.1          69.8         95.9          NaN
53          59.7       60.5          65.8         73.3          NaN

[80 rows x 11 columns]

In [21]:
#Q13. Feature Creation – 6 Marks

df['Average_Technical_Score']=(df['Python_Score']+df['SQL_Score']+df['Pandas_Score']+df['NumPy_Score'])
print(df)

   Student_ID            Name  Gender        Department   Age  Attendance  \
0     STU1001     Rahul Varma    Male  Computer Science  25.0        74.7
1     STU1002    Kiran Pillai    Male  Computer Science  24.0        75.5
2     STU1003  Fathima Joseph  Female       Electronics  21.0        60.5
3     STU1004    Rahul Sharma  Female      Data Science  25.0        80.4
4     STU1005       Asha Nair  Female      Data Science  22.0        71.4
..        ...             ...     ...               ...   ...         ...
75    STU1076     Priya Kumar  Female  Computer Science  24.0        99.3
76    STU1077      Amal Kumar    Male      Data Science   NaN        93.8
77    STU1078  Fathima Sharma    Male  Computer Science  19.0        86.4
78    STU1079    Meera Thomas    Male       Electronics  23.0        99.4
79    STU1080      Diya Varma    Male       Electronics  19.0        86.4

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score  \
0           89.4       86.3          81.9         76.7         82.7
1           70.3       63.1          65.1         62.3         60.3
2           79.9       80.4          65.3         68.0         67.1
3           65.8       50.7          52.6         48.8         57.2
4           90.1       82.9          72.4         87.7         81.9
..           ...        ...           ...          ...          ...
75          46.9       57.6          29.5         57.1         47.2
76          45.8       43.4          58.1         38.8         43.5
77          70.4       75.7          98.2         76.7         75.2
78          64.6       66.5          61.8         52.5         63.4
79          80.5       94.3          58.6         74.9         78.6

    Average_Technical_Score
0                     334.3
1                     260.8
2                     293.6
3                     217.9
4                     333.1
..                      ...
75                    191.1
76                    186.1
77                    321.0
78                    245.4
79                    308.3

[80 rows x 12 columns]

In [33]:
#Q14. GroupBy Analysis – 6 Marks

file_path='/content/student_performance.csv'
df=pd.read_csv(file_path)
print(df.groupby('Department').agg({'Final_Score':['mean','max','min']}))
print(df.sort_values(by='Final_Score',ascending=False))

                 Final_Score
                        mean   max   min
Department
 Data Science      55.100000  55.1  55.1
Commerce           67.825000  83.7  54.6
Computer Science   71.479310  96.0  40.6
Computer science   46.700000  46.7  46.7
Data Science       71.324000  97.0  43.5
Electronics        72.846154  86.9  51.2
data science       66.900000  66.9  66.9
   Student_ID           Name    Gender        Department   Age  Attendance  \
48    STU1049    Asha Sharma      Male      Data Science  22.0        91.3
61    STU1062   Kiran Pillai    Female  Computer Science  19.0        83.8
40    STU1041    Amal Pillai    Female  Computer Science  25.0        97.7
55    STU1056    Vivek Varma      Male      Data Science  22.0        81.0
57    STU1058    Diya Thomas    Female  Computer Science  23.0        83.5
..        ...            ...       ...               ...   ...         ...
34    STU1035   Rahul Pillai    Female      Data Science  22.0        82.5
76    STU1077     Amal Kumar      Male      Data Science   NaN        93.8
26    STU1027  Aditya Pillai    Female  Computer Science  25.0        79.6
42    STU1043    Sneha Varma   female       Data Science  19.0        74.4
53    STU1054    Maya Sharma      Male      Data Science  19.0        82.5

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
48          88.9       95.0           NaN         94.5         97.0
61         100.0      100.0          89.4         91.4         96.0
40          94.3       91.0          73.1         91.2         94.5
55          87.0       95.1          88.4         75.7         93.3
57          93.1       78.8          91.6         83.8         92.3
..           ...        ...           ...          ...          ...
34          41.4       44.4          53.8         43.2         44.2
76          45.8       43.4          58.1         38.8         43.5
26          44.0       52.5          25.0         25.0         40.6
42          71.8       79.1          69.8         95.9          NaN
53          59.7       60.5          65.8         73.3          NaN

[80 rows x 11 columns]

In [ ]:
#Q15. NumPy and Pandas Integration – 6 Marks